const menuItemsData = [
  {
    id: 0,
    name: "Bûche au chocolat",
    picture: "buche_chocolat",
    category: "dessert",
  },
  {
    id: 1,
    name: "Pain aux céréales",
    picture: "bpain",
    category: "accompagnement",
  },
  {
    id: 3,
    name: "Rosé",
    picture: "rose",
    category: "boisson",
  },
  {
    id: 4,
    name: "Verrines sucrées",
    picture: "verrines_dessert",
    category: "dessert",
  },
  {
    id: 5,
    name: "Cake",
    picture: "cake",
    category: "dessert",
  },
  {
    id: 6,
    name: "Cake façon crumble",
    picture: "cake_table",
    category: "dessert",
  },
  {
    id: 7,
    name: "Cupcakes au chocolat",
    picture: "cupcakes",
    category: "dessert",
  },
  {
    id: 8,
    name: "Muffins à la crème",
    picture: "mussins_creme",
    category: "dessert",
  },
  {
    id: 9,
    name: "Cake à la cannelle",
    picture: "cake_cinnamon",
    category: "dessert",
  },
  {
    id: 10,
    name: "Bircuits au pain d'épice",
    picture: "cookies_gingerbread",
    category: "dessert",
  },
  {
    id: 11,
    name: "Eclairs au chocolat",
    picture: "eclairs_chocolat",
    category: "dessert",
  },
  {
    id: 12,
    name: "Thé à l'orange",
    picture: "the",
    category: "gouter",
  },
  {
    id: 13,
    name: "Cocktails",
    picture: "cocktails",
    category: "boisson",
  },
  {
    id: 14,
    name: "Rôti de porc",
    picture: "ham",
    category: "plat",
  },
  {
    id: 16,
    name: "Pop corn",
    picture: "popcorn",
    category: "gouter",
  },
  {
    id: 17,
    name: "marshmallow",
    picture: "marshmallow",
    category: "gouter",
  },
  {
    id: 18,
    name: "Pavé de saumon",
    picture: "salmon",
    category: "plat",
  },
  {
    id: 19,
    name: "Pains au chocolat",
    picture: "bread-chocolat",
    category: "gouter",
  },
  {
    id: 20,
    name: "Chapon farci",
    picture: "chapon_farci",
    category: "plat",
  },
  {
    id: 21,
    name: "Roti de boeuf",
    picture: "roti_boeuf",
    category: "plat",
  },
  {
    id: 22,
    name: "Verrines sucrées",
    picture: "verrines_dessert",
    category: "dessert",
  },
  {
    id: 23,
    name: "pâté en croute",
    picture: "pate_croute",
    category: "entree",
  },
  {
    id: 24,
    name: "Verrines sucrées",
    picture: "verrines_dessert",
    category: "dessert",
  },
  {
    id: 25,
    name: "Noix de Saint Jacques",
    picture: "noix_saint_jacques",
    category: "entree",
  },
  {
    id: 26,
    name: "Fruits de mer",
    picture: "fruits_de_mer",
    category: "entree",
  },
  {
    id: 27,
    name: "Rôti aux asperges",
    picture: "aspergus",
    category: "plat",
  },
];

export default menuItemsData;
